apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-consumer
  namespace: kafka
spec:
  selector:
    matchLabels:
      name: deploy-consumer
  replicas: 1
  template:
    metadata:
      labels:
        name: deploy-consumer
    spec:
      containers:
      - name: consumer
        image: josephmarroquin/go-consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_AUTH
          value: "YOUR_PASSWORD"
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: secret-env-consumer
              key: PORT
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: secret-env-consumer
              key: KAFKA_BROKERS
        - name: KAFKA_TOPIC
          valueFrom:
            secretKeyRef:
              name: secret-env-consumer
              key: KAFKA_TOPIC
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password