apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: service-producer-rust
spec:
  ports:
  - name: producer-port
    port: 8080
    targetPort: 8080
  selector:
      name: deploy-producer-rust
  type: LoadBalancer